### PR TITLE
Truncate the styles table during update to remove old OL 2.x styles.

### PR DESCRIPTION
**Pull request by mstenta**

### CODE REVIEW

**Comment by drupol** [comment]
Do you think it's possible to recover data from 2.x ?

**Comment by mstenta** [comment]
There are a few places in that update hook where data is being deleted. It is a bigger job to try to save any of it - and may not be possible due to the changes in the data architecture.

**Comment by drupol** [comment]
Ok then.

**Comment by drupol** [comment]
Don't forget to add a new hook_update_n() with proper comment or else it won't be executed.

**Comment by mstenta** [comment]
Well in this case we only want it to be executed when updating from OL2, which is what hook_update_7350() is for.  So I think it should be included in that update.  Most people will not need it... only the people who are upgrading from OL2.

**Comment by mstenta** [comment]
But it really doesn't matter... I can put it in a new update hook if that is your preference.

**Comment by mstenta** [comment]
Woo! :+1:

**Pull request merged**
