### PR TITLE
New editing toolbar for Openlayers Geofield.

### PR DESCRIPTION
**Pull request by drupol**
Developping a new control, an editing toolbar to provide more options for the geofield component.

edit map openlayers_geofield_map_geofield - d7x x230 local

Do not forget to convert your sources. The factory service "openlayers.Source:Geofield" has been replaced with "openlayers.Source:Vector".

### CODE REVIEW

**Comment by mstenta** [comment]
I just gave this a try. It looks and works great! Awesome work Pol!

Two questions came to mind as I was trying it out:

1) How does this interact with the fields that are added below the map by the Geofield Component? ("Type of interaction" and "Geometry type") I notice that those don't change if you click the new icon buttons. And as a matter of fact, they seem to be broken on their own now. Is that because of this change? Do you plan to remove them entirely? I sort of like having the option of choosing either approach.

2) Can we add options to enable/disable certain buttons? I don't really need the ability to draw "triangles", for example.

3) Does this work on mobile devices? I haven't tested it yet, but that is necessary for my project. That is one of the reasons that I actually liked the form elements that were below the map - they made mobile interaction a little easier. That's another reason why it might be nice to have the choice between them - or maybe even allow them to switch automatically depending on the device being used.

**Comment by mstenta** [comment]
I think I found a bug with it... still trying to figure out what causes it... but under certain circumstances it becomes impossible to select a feature. I was trying out a bunch of the features, and then tried to select a point and delete it, but it would not select.  I will see if I can isolate it...

**Comment by drupol** [comment]
Hello,

I haven't tested on mobile, but I'm pretty confident as I'm using the API,
nothing else.
I'm going to push an update in a few minute, code is even more streamlined
and easier to understand.

 -*φol d.*-

**Comment by drupol** [comment]
Try now. Added a couple of new options. I will probably do something to
customize the buttons.

 -*φol d.*-

**Comment by drupol** [comment]
openlayers-geofield

**Comment by mstenta** [comment]
Nice! What is a "multi[point|line|polygon]"? Does that mean multiple shapes that are all considered the same "feature"?

Is that connected to the Geofield settings at all?  There is a setting to say whether all features should be part of the same collection, or if they should be stored as separate fields...

**Comment by drupol** [comment]
I will sort this out soon, still a lot of work to come.

**Comment by mstenta** [comment]
Cool.  I will hold off on using this right away.  FYI: I am pushing to complete my farmOS transition to OL 3 by the end of this week (https://www.drupal.org/node/2448181).  So stability is my #1 priority right now.  I'm excited to see this feature come together though!  And I'll be happy to help with it once this week is over.

**Comment by mstenta** [comment]
FYI: This error is visible in maps with the Geofield Component when this branch is active (see screenshot)

And it is not possible to use the "Type of interaciton" field below the map to select/modify/draw features.  Perhaps they are related?  Hope that helps...

screenshot from 2015-07-29 13 29 10

**Comment by drupol** [comment]
Is it working usually ?

**Comment by mstenta** [comment]
Yes, it's working on the 7.x-3.x branch. My guess is it has to do with the changes being made in Geofield.js (for the Component... not the new Control).

**Comment by drupol** [comment]
Working on it...

**Comment by drupol** [comment]
Fixed, now let's go back to the issue.

**Comment by drupol** [comment]
Do not forget to convert your source. The factory service "openlayers.Source:Geofield" has been replaced with "openlayers.Source:Vector".

**Comment by mstenta** [comment]
> Do not forget to convert your sources. The factory service "openlayers.Source:Geofield"
> has been replaced with "openlayers.Source:Vector".

Shouldn't there be some kind of automated update provided? Right now this means anyone updating their repository will have their Geofields break. At the very least it needs to be documented exactly how to "convert your sources".

**Pull request merged**
